import json
from pathlib import Path


def load_final_analysis() -> dict:
    """
    Load the final interview analysis generated by final_analyzer.py.
    """
    path = Path("output/prep/final_analysis.json")
    if not path.exists():
        raise FileNotFoundError(f"Final analysis not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def format_list(items: list) -> str:
    """
    Convert a list of strings into readable bullet points.
    """
    if not items:
        return "- None reported."
    return "\n".join(f"- {item}" for item in items)


def generate_report(data: dict) -> str:
    """
    Convert the structured JSON analysis into a
    human-readable interview report.
    """
    code_perf = data.get("code_performance", {})
    code_section = ""
    if code_perf and code_perf.get("attempted", 0) > 0:
        code_section = f"""
---

## Code Submissions Performance

- **Coding Exercises Attempted**: {code_perf.get("attempted", 0)}
- **Coding Exercises Passed**: {code_perf.get("passed", 0)}
- **Average Execution & Correctness Score**: {code_perf.get("average_score", 0)}/100

{code_perf.get("notes", "")}
"""

    integrity = data.get("integrity", {})
    integrity_section = ""
    if integrity and (integrity.get("flag_count", 0) > 0 or integrity.get("flagged_for_review", False)):
        flags_str = ""
        flags = integrity.get("flags", [])
        if flags:
            flags_str = "\n".join(
                f"- **{f.get('type', '').replace('_', ' ').title()}**: {f.get('details', '')} (at {f.get('timestamp', '')})"
                for f in flags
            )
        else:
            flags_str = "- No detailed flag logs available."

        status_text = "**FLAGGED FOR REVIEW** ⚠️" if integrity.get("flagged_for_review", False) else "Pass with minor warnings"

        integrity_section = f"""
---

## Integrity & Proctoring Report

- **Proctoring Review Status**: {status_text}
- **Total Flag Events**: {integrity.get("flag_count", 0)}
- **Interruption/Tab Switch Notes**: {integrity.get("notes", "No additional notes.")}

### Detailed Flag Timeline:
{flags_str}
"""
    else:
        integrity_section = """
---

## Integrity & Proctoring Report

- **Proctoring Review Status**: Pass (No violations detected) ✅
"""

    speech_analysis = data.get("speech_analysis", {})
    speech_section = ""
    if speech_analysis and speech_analysis.get("wpm", 0) > 0:
        speech_section = f"""
---

## Speech & Delivery Analysis

- **Speaking Pace (WPM)**: {speech_analysis.get("wpm", 0)}
- **Filler Words Used**: {speech_analysis.get("total_filler_words", 0)}

{speech_analysis.get("feedback", "")}
"""

    body_analysis = data.get("body_language_analysis", {})
    body_section = ""
    if body_analysis and body_analysis.get("eye_contact_score") is not None:
        body_section = f"""
---

## Body Language & Engagement

- **Eye Contact Score**: {body_analysis.get("eye_contact_score", 0)}%

{body_analysis.get("feedback", "")}
"""

    report = f"""# FirstRound Interview Report

## Overall Assessment

| Metric | Score |
|---|---:|
| Overall Score | {data.get("overall_score", 0)}/100 |
| Technical Score | {data.get("technical_score", 0)}/100 |
| Communication Score | {data.get("communication_score", 0)}/100 |
| JD Alignment | {data.get("jd_alignment_score", 0)}/100 |

### Recommendation

**{data.get("recommendation", "Not Available")}**

---

## Strengths

{format_list(data.get("strengths", []))}

---

## Weaknesses

{format_list(data.get("weaknesses", []))}

---

## Technical Gaps

{format_list(data.get("technical_gaps", []))}

---

## Communication Gaps

{format_list(data.get("communication_gaps", []))}

---

## Improvement Plan

{format_list(data.get("improvement_plan", []))}
{speech_section}
{body_section}
{code_section}
{integrity_section}

---

## Summary

{data.get("summary", "No summary available.")}
"""

    return report


def main() -> None:
    final_analysis = load_final_analysis()
    report = generate_report(final_analysis)
    output_path = Path("output/prep/final_report.md")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")

    print("Final report generated successfully.")
    print(f"Saved to: {output_path}")
    print()
    print(report)


if __name__ == "__main__":
    main()
