import json
from pathlib import Path


def load_final_analysis() -> dict:
    """
    Load the final interview analysis generated by final_analyzer.py.
    """

    path = Path("output/prep/final_analysis.json")

    if not path.exists():
        raise FileNotFoundError(
            f"Final analysis not found: {path}"
        )

    return json.loads(
        path.read_text(encoding="utf-8")
    )


def format_list(items: list) -> str:
    """
    Convert a list of strings into readable bullet points.
    """

    if not items:
        return "- None reported."

    return "\n".join(
        f"- {item}"
        for item in items
    )


def generate_report(data: dict) -> str:
    """
    Convert the structured JSON analysis into a
    human-readable interview report.
    """

    report = f"""# FirstRound Interview Report

## Overall Assessment

| Metric | Score |
|---|---:|
| Overall Score | {data.get("overall_score", 0)}/100 |
| Technical Score | {data.get("technical_score", 0)}/100 |
| Communication Score | {data.get("communication_score", 0)}/100 |
| JD Alignment | {data.get("jd_alignment_score", 0)}/100 |

### Recommendation

**{data.get("recommendation", "Not Available")}**

---

## Strengths

{format_list(data.get("strengths", []))}

---

## Weaknesses

{format_list(data.get("weaknesses", []))}

---

## Technical Gaps

{format_list(data.get("technical_gaps", []))}

---

## Communication Gaps

{format_list(data.get("communication_gaps", []))}

---

## Improvement Plan

{format_list(data.get("improvement_plan", []))}

---

## Summary

{data.get("summary", "No summary available.")}
"""

    return report


def main() -> None:

    final_analysis = load_final_analysis()

    report = generate_report(
        final_analysis
    )

    output_path = Path(
        "output/prep/final_report.md"
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path.write_text(
        report,
        encoding="utf-8",
    )

    print("Final report generated successfully.")
    print(f"Saved to: {output_path}")
    print()
    print(report)


if __name__ == "__main__":
    main()